### ISSUE TITLE
Runtime error (error code 59)

### ISSUE THREAD

**Issue by mhtopixag** [miyako/4d-plugin-ix-websocket#1]
Hi Keisuke,

if the encryption of client-server connections is activated, a runtime error will occur as soon as you quit a client. This is also reproducable with the structure which is provided in the source code sample of the plugin.
It seems like the following line is causing the problem on exiting the client:
`PA_Variable result = PA_ExecuteCommandByID( /*Current process name*/1392, params, 0 );`

Screenshots:
https://imgur.com/UEeRbzV (runtime error)
https://imgur.com/Rb6iv0k (encryption setting)

Cheers,
Michael

**Comment by miyako** [comment]
Hello, it is important to **specify the platform** (mac or windows) since a "crash on quit" is rather typical to DLL/dylib loader and how open-source libraries are typically written to be loaded once by the main application, not as a plugin.

**Comment by mhtopixag** [comment]
It has just been retestet with 4Dv18 (18.247531) and the error still persists on both macOS (Mojave 10.14.6) and Windows (Windows 10 with all current updates).

Screenshot macOS:
[https://imgur.com/a/gShTR3z](https://imgur.com/a/gShTR3z)
Screenshot Win:
[https://imgur.com/UEeRbzV](https://imgur.com/UEeRbzV)

Also it doesn't matter which client (macOS oder Windows) is connecting and quitting.

To reproduce the problem:
- use the sample application provided in the plugin source and open it on a server (macOS or Win)
- activate the encryption as in [https://imgur.com/Rb6iv0k](https://imgur.com/Rb6iv0k)
- connect client to server (macOS or Win)
- quit client
=> runtime error number 59 on server

I hope this helps. I'd be glad to assist you if you need more information.

**Comment by miyako** [comment]
are you saying that if encryption is disabled, there is no issue?

**Comment by mhtopixag** [comment]
Exactly!

**Comment by miyako** [comment]
interesting, I will remove the call to "get process name" (it was checking for $xx) and move all cleanup code to plugin-deinit

**Comment by miyako** [comment]
could you please try release v3.3?

**Comment by mhtopixag** [comment]
Where can I get the new version? In the repository it's still version 3.2.

**Comment by miyako** [comment]
releases are in the "releases" section on GitHub
 
https://github.com/miyako/4d-plugin-ix-websocket/releases

**Comment by mhtopixag** [comment]
Thank you so much, the error does not occur any more.
Now we can continue with our websocket prototyping.
