### ISSUE TITLE
Plugin does not work with SSL

### ISSUE THREAD

**Issue by mhtopixag** [miyako/4d-plugin-ix-websocket#3]
Hi Keisuke,

this plugin seems to lack support for SSL, other than IXWebSocket, which has SSL support.
Or is there some hidden/undocumented options when creating the websocket server?

Cheers,
Michael

**Comment by miyako** [comment]
I think the library version is too old.

I just rebuilt a release with TLS link (3.6.0) but there is no API to configure TLS ([setTLSOptions](https://machinezone.github.io/IXWebSocket/usage/)) yet, at the C level. a library update and refactoring of the code seems necessary.

maybe the client side would work (wss:// URL), but not the server side.

**Comment by miyako** [comment]
I have sent a private invite to the new repo. with TLS support
